version: '2'
services:
    jhipstersampleapplicationmonolith-app:
        image: jhipstersampleapplicationmonolith
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstersampleapplicationmonolith-postgresql:5432/jhipsterSampleApplicationMonolith
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersampleapplicationmonolith-postgresql:
        extends:
            file: postgresql.yml
            service: jhipstersampleapplicationmonolith-postgresql
